version: '3.8'

services:
  completion-llm:
    build:
      context: .
      dockerfile: Dockerfile.completion
    ports:
      - "8001:8000"
    environment:
      - CUDA_VISIBLE_DEVICES=0
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["python", "completion_service.py"]

  analysis-llm:
    build:
      context: .
      dockerfile: Dockerfile.analysis
    ports:
      - "8002:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./logs:/app/logs
    command: ["python", "analysis_service.py"]

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "8000:8000"
    depends_on:
      - completion-llm
      - analysis-llm
    volumes:
      - ./logs:/app/logs
    command: ["python", "api_gateway.py"]

volumes:
  models:
  logs:
